#!/bin/bash
# 
# pdfredux - a script to reduce size and optimize PDFs
#
# By Nicola Ferralis <feranick@hotmail.com>
# 
# This is script is licensed throughthe GNU Public license v.2.0
#

version='20200907b'

if [ "$1" = "" -o "$1" = "-h" ]; then
	echo
	echo " PDFredux v."$version
	echo " Usage:"
	echo " 	pdfredux <filename (with extension)>"
	echo
else
    if [ "$1" = "-v" ]; then
        echo
        echo "Pdfredux: v."$version
        echo "Nicola Ferralis <feranick@hotmail.com>" 
        echo
    else
	echo
	if [ -f $1 ]; then
	   base=$(basename $1 .pdf)
           echo " Reducing size of \"$1\" into \"$base-red.pdf\"..."
           #gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOUTPUTFILE=$1-red.pdf $1.pdf
           #gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dFastWebView -sOUTPUTFILE=$base-red.pdf  $1
	   gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dPDFSETTINGS=/ebook -sOUTPUTFILE=$base-red.pdf  $1
	   echo " Done." 		
	else
	   echo " File \"$1\" does NOT exists."
    	fi
	echo
    fi
fi
